### ISSUE TITLE
RE: Coverage Interfaces

### ISSUE THREAD

**Issue by mballance** [umarcor/osvb#2]
This is in response to comments on accessing UCIS/UCDB. The projects [pyucis](https://github.com/fvutils/pyucis) and [pyucis-viewer](https://github.com/fvutils/pyucis-viewer) provide some level of support. pyucis can write functional coverage data in UCIS XML-interchange format, and to Mentor UCDB via the UCIS library provided by Questa. pyucis-viewer provides a simple bar-chart graphical viewer for coverage data read via pyucis.

**Comment by umarcor** [comment]
Thanks Matthew! I was not notified about this issue, and I had not seen it. I fixed the watch settings now.

I updated the docs for adding your clarifications about pyucis and pyucis-viewer: https://github.com/umarcor/osvb/commit/96f4a5c7ac0e3d627a4ade294954137f852fff73.
